# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: search.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csearch.proto\x12\x06search\"\x1e\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\"<\n\x0cSearchResult\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0c\n\x04link\x18\x02 \x01(\t\x12\x0f\n\x07snippet\x18\x03 \x01(\t\"7\n\x0eSearchResponse\x12%\n\x07results\x18\x01 \x03(\x0b\x32\x14.search.SearchResult2J\n\rSearchService\x12\x39\n\x06Search\x12\x15.search.SearchRequest\x1a\x16.search.SearchResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'search_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SEARCHREQUEST']._serialized_start=24
  _globals['_SEARCHREQUEST']._serialized_end=54
  _globals['_SEARCHRESULT']._serialized_start=56
  _globals['_SEARCHRESULT']._serialized_end=116
  _globals['_SEARCHRESPONSE']._serialized_start=118
  _globals['_SEARCHRESPONSE']._serialized_end=173
  _globals['_SEARCHSERVICE']._serialized_start=175
  _globals['_SEARCHSERVICE']._serialized_end=249
# @@protoc_insertion_point(module_scope)
